# Generated by Django 3.0.6 on 2020-05-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypicnics', '0005_auto_20200527_1157'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picnicuser',
            name='picnics',
            field=models.ManyToManyField(blank=True, to='mypicnics.Picnic'),
        ),
    ]
