# Generated by Django 3.0.6 on 2020-06-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200630_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='picnicuser',
            name='hasNotifications',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='picnicuser',
            name='notifs',
            field=models.ManyToManyField(blank=True, to='users.Notification'),
        ),
    ]
