# Generated by Django 3.0.6 on 2020-07-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200701_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='extra',
            field=models.TextField(blank=True, help_text="Send a message to your critiquer, if you'd like! What about their feedback did you find helpful?"),
        ),
    ]
