# Generated by Django 3.0.6 on 2020-07-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='extra',
            field=models.TextField(blank=True, help_text="Send a message to your critiquer, if you'd like! What about their feedback did you find helpful?", verbose_name='Leave a note'),
        ),
    ]
