# Generated by Django 3.0.5 on 2020-05-08 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypicnics', '0002_auto_20200507_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picnic',
            old_name='picnic_id',
            new_name='key',
        ),
        migrations.AddField(
            model_name='picnic',
            name='background_image',
            field=models.ImageField(default='default.jpg', upload_to='backgrounds'),
        ),
        migrations.AlterField(
            model_name='critique',
            name='critique',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mypicnics.Feedback'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='artwork',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mypicnics.Artwork'),
        ),
    ]
