# Generated by Django 3.0.5 on 2020-05-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypicnics', '0003_auto_20200508_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='num_critiques',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='num_uploads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='picnic',
            name='background_image',
            field=models.ImageField(default='default.png', help_text='Upload a background image for your picnic.', upload_to='backgrounds'),
        ),
        migrations.AlterField(
            model_name='picnic',
            name='description',
            field=models.TextField(help_text='Enter a description of your picnic.'),
        ),
    ]
