# Generated by Django 3.0.6 on 2020-05-27 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mypicnics', '0004_auto_20200509_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
