# Generated by Django 3.0.6 on 2020-05-27 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mypicnics', '0006_auto_20200527_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critique',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='upload',
            name='date_uploaded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
