# Generated by Django 3.0.6 on 2020-06-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypicnics', '0007_auto_20200527_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artwork',
            field=models.ImageField(null=True, upload_to='artworks'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(help_text='Describe this piece, the mediums you used, the ideas behind it, etc.'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='feedback',
            field=models.TextField(help_text='What aspects of this piece would you like feedback on? (color, composition, anatomy, etc.)'),
        ),
    ]
