# Generated by Django 3.0.6 on 2020-06-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypicnics', '0010_auto_20200627_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='bread1',
            field=models.TextField(verbose_name='Bread (Top)'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='bread2',
            field=models.TextField(verbose_name='Bread (Bottom)'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='middle',
            field=models.TextField(verbose_name='Filling'),
        ),
    ]
