# Generated by Django 3.0.6 on 2020-06-28 01:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mypicnics', '0012_auto_20200628_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='critique',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='date_uploaded',
        ),
        migrations.AddField(
            model_name='artwork',
            name='date_uploaded',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='feedback',
            name='date_added',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='bread1',
            field=models.TextField(help_text='Open with a compliment. What first strikes you about this piece and why?', verbose_name='Layer 1 - Bread'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='bread2',
            field=models.TextField(help_text='Close off with another positive comment. What do you like about this piece overall? How does it make you feel? Do you have any questions about this piece?', verbose_name='Layer 3 - Bread'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='middle',
            field=models.TextField(help_text="Here is where you will put the 'meat' of your critique. What could be improved or refined? Keep in mind the aspects that the artist specifically wanted feedback on.", verbose_name='Layer 2 - Filling'),
        ),
    ]
