# Generated by Django 3.0.6 on 2020-06-30 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mypicnics', '0013_auto_20200628_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='date_uploaded',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date_added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
