# Generated by Django 3.0.5 on 2020-10-12 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypicnics', '0015_feedback_thanks_given'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='artworks')),
            ],
        ),
        migrations.AlterField(
            model_name='picnic',
            name='background_image',
            field=models.ImageField(default='backgrounds/default.png', help_text='Upload a background image for your picnic.', upload_to='backgrounds'),
        ),
        migrations.CreateModel(
            name='ImgLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypicnics.Artwork')),
                ('img', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mypicnics.Img')),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='uploads',
            field=models.ManyToManyField(default=None, through='mypicnics.ImgLink', to='mypicnics.Img'),
        ),
    ]
