# Generated by Django 3.0.5 on 2020-10-12 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypicnics', '0016_auto_20201012_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imglink',
            name='group',
        ),
        migrations.RemoveField(
            model_name='imglink',
            name='img',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='uploads',
        ),
        migrations.DeleteModel(
            name='Img',
        ),
        migrations.DeleteModel(
            name='ImgLink',
        ),
    ]
