# Generated by Django 3.0.5 on 2020-10-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypicnics', '0017_auto_20201012_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='artworks')),
            ],
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='artwork',
        ),
        migrations.AddField(
            model_name='artwork',
            name='artwork',
            field=models.ManyToManyField(to='mypicnics.Image'),
        ),
    ]
