# Generated by Django 3.0.5 on 2020-10-12 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypicnics', '0018_auto_20201012_2232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Img',
        ),
    ]
