# Generated by Django 3.0.5 on 2020-10-12 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypicnics', '0019_auto_20201012_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='cover',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='mypicnics.Img'),
        ),
    ]
